<?php

namespace InviteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitesRepository extends EntityRepository
{
}
