<?php

namespace CreationplatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * creationplatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class creationplatRepository extends EntityRepository
{
}
